const DefaultConf = /**/ {
  client: {
    dogmadual: {
      metadata: { title: 'DOGMADUAL.com' },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'SearchBox',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Pagination',
          'windowGetDimensions',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'PublicProfile',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'AppStore',
          'SocketIoHandler',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
          'EventBus',
          'ClientEvents',
          'Repository',
        ],
        dogmadual: [
          'AppShellDogmadual',
          'RouterDogmadual',
          'AppStoreDogmadual',
          'CssDogmadual',
          'LogInDogmadual',
          'LogOutDogmadual',
          'SignUpDogmadual',
          'SocketIoDogmadual',
          'SettingsDogmadual',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/settings', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/log-in', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/sign-up', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/log-out', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/account', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/recover', client: 'Dogmadual', ssr: 'Dogmadual' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
        {
          folder: './node_modules/dexie/dist',
          public_folder: '/dist/dexie',
          import_name: 'dexie',
          import_name_build: '/dist/dexie/dexie.mjs',
        },
      ],
      services: ['core', 'file', 'user'],
    },
    nexodev: {
      metadata: {
        title: 'Nexodev - ERP, CRM Development & Cloud DevOps Services',
        description:
          'Nexodev specializes in developing and implementing robust ERP & CRM systems, along with providing expert cloud DevOps services. We empower businesses to streamline operations and achieve strategic goals.',
        keywords: [
          'ERP development',
          'CRM development',
          'cloud DevOps',
          'ERP implementation',
          'CRM implementation',
          'business process automation',
          'enterprise resource planning',
          'customer relationship management',
          'cloud infrastructure',
          'IT automation',
        ],
        author: 'https://github.com/underpostnet',
        baseBuildIconReference: './src/client/public/nexodev/assets/logo/nexodev-purple-t.png',
        thumbnail: 'assets/banner/nexodev.jpg',
        themeColor: '#69055F',
        backgroundImage: 'assets/background/white-purple-2.jpg',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'SearchBox',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Pagination',
          'windowGetDimensions',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'PublicProfile',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'AppStore',
          'SocketIoHandler',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
          'Panel',
          'PanelForm',
          'EventBus',
          'ClientEvents',
          'Repository',
        ],
        chart: ['connectedScatterplotChart'],
        nexodev: [
          'AppShellNexodev',
          'RouterNexodev',
          'AppStoreNexodev',
          'CssNexodev',
          'LogInNexodev',
          'LogOutNexodev',
          'SignUpNexodev',
          'CalendarNexodev',
          'DashboardNexodev',
          'StreamNexodev',
          'SocketIoNexodev',
          'SettingsNexodev',
        ],
      },
      views: [
        { path: '/', title: 'ERP, CRM Development & Cloud DevOps Services', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/blog', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/settings', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/log-in', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/sign-up', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/log-out', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/account', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/calendar', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/dashboard', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/stream', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/docs', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/content', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/cloud', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/chat', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/settings', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/wallet', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/recover', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/default-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/user-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/instance-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/cron-management', client: 'Nexodev', ssr: 'Nexodev' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/easymde/dist', public_folder: '/dist/easymde' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        { folder: './node_modules/d3/dist', public_folder: '/dist/d3' },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
        {
          folder: './node_modules/marked/lib',
          public_folder: '/dist/marked',
          import_name: 'marked',
          import_name_build: '/dist/marked/marked.esm.js',
        },
        { folder: './node_modules/@fullcalendar', public_folder: '/dist/@fullcalendar' },
        { folder: './node_modules/rrule/dist/es5', public_folder: '/dist/rrule' },
        {
          folder: './node_modules/dexie/dist',
          public_folder: '/dist/dexie',
          import_name: 'dexie',
          import_name_build: '/dist/dexie/dexie.mjs',
        },
      ],
      services: ['default', 'core', 'user', 'document', 'file', 'crypto', 'instance', 'event-scheduler', 'cron'],
    },
  },
  ssr: {
    Nexodev: {
      head: ['Seo', 'Pwa', 'NexodevScripts', 'Css'],
      body: ['CacheControl', 'NexodevSplashScreen', 'SwaggerDarkMode'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      views: [
        {
          path: '/offline',
          title: 'No Network Connection',
          client: 'NoNetworkConnection',
          head: [],
          body: [],
          offlineDefault: true,
        },
        {
          path: '/maintenance',
          title: 'Server Maintenance',
          client: 'Maintenance',
          head: [],
          body: [],
          maintenanceDefault: true,
        },
        { path: '/test', title: 'Test', client: 'Test', head: [], body: [] },
      ],
    },
    Dogmadual: {
      head: ['DogmadualScripts', 'Css'],
      body: ['CacheControl', 'DefaultSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      views: [
        {
          path: '/offline',
          title: 'No Network Connection',
          client: 'NoNetworkConnection',
          head: [],
          body: [],
          offlineDefault: true,
        },
        {
          path: '/maintenance',
          title: 'Server Maintenance',
          client: 'Maintenance',
          head: [],
          body: [],
          maintenanceDefault: true,
        },
        { path: '/test', title: 'Test', client: 'Test', head: [], body: [] },
      ],
    },
  },
  server: {
    'dogmadual.com': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        proxy: [80, 443],
        redirect: 'https://www.dogmadual.com',
      },
    },
    'www.dogmadual.com': {
      '/': {
        client: 'dogmadual',
        runtime: 'nodejs',
        apis: ['user', 'file'],
        origins: [],
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: {
          provider: 'mongoose',
          host: 'env:DB_HOST',
          name: 'env:DB_NAME_DOGMADUAL',
          replicaSet: 'env:DB_REPLICA_SET:rs0',
          authSource: 'env:DB_AUTH_SOURCE:admin',
          user: 'env:DB_USER:',
          password: 'env:DB_PASSWORD:',
        },
        valkey: { port: 'env:VALKEY_PORT', host: 'env:VALKEY_HOST' },
        mailer: {
          sender: { email: 'env:MAILER_SENDER_EMAIL', name: 'env:MAILER_SENDER_NAME' },
          transport: {
            host: 'env:SMTP_HOST',
            port: 'env:SMTP_PORT',
            secure: true,
            auth: { user: 'env:SMTP_AUTH_USER', pass: 'env:SMTP_AUTH_PASS' },
          },
        },
      },
    },
    'nexodev.org': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        proxy: [80, 443],
        redirect: 'https://www.nexodev.org',
      },
    },
    'www.nexodev.org': {
      '/': {
        client: 'nexodev',
        runtime: 'nodejs',
        apis: ['default', 'user', 'test', 'document', 'file', 'crypto', 'instance', 'event-scheduler', 'cron', 'core'],
        origins: ['https://www.nexodev.org', 'https://underpost.net', 'https://underpostnet.github.io'],
        ws: 'core',
        peer: true,
        docs: {
          coveragePath: './',
          jsJsonPath: './typedoc.json',
          references: [
            './src/client/public/nexodev/docs/references/Getting started.md',
            './src/client/public/nexodev/docs/references/Command Line Interface.md',
            './src/client/public/nexodev/docs/references/Baremetal Management.md',
            './src/client/public/nexodev/docs/references/Cron Jobs Management.md',
            './src/client/public/nexodev/docs/references/DB and Backup Management.md',
            './src/client/public/nexodev/docs/references/Deploy to K8S.md',
            './src/client/public/nexodev/docs/references/Deploy custom instance to K8S.md',
            './src/client/public/nexodev/docs/references/Image Management.md',
            './src/client/public/nexodev/docs/references/LXD Management.md',
            './src/client/public/nexodev/docs/references/Main cluster lifecycle commands.md',
            './src/client/public/nexodev/docs/references/Monitor cluster.md',
            './src/client/public/nexodev/docs/references/Running Separate Client and API Servers for Development.md',
            './src/client/public/nexodev/docs/references/SSH Management.md',
            './src/client/public/nexodev/docs/references/Static Generator.md',
            './src/client/public/nexodev/docs/references/PWA and SSR Views.md',
            './src/client/public/nexodev/docs/references/Main cluster lifecycle commands.md',
            './src/client/public/nexodev/docs/references/Observability and Events.md',
            './src/client/public/nexodev/docs/references/Testing and Coverage.md',
          ],
        },
        proxy: [80, 443],
        db: {
          provider: 'mongoose',
          host: 'env:DB_HOST',
          name: 'env:DB_NAME_NEXODEV',
          replicaSet: 'env:DB_REPLICA_SET:rs0',
          authSource: 'env:DB_AUTH_SOURCE:admin',
          user: 'env:DB_USER:',
          password: 'env:DB_PASSWORD:',
        },
        valkey: { port: 'env:VALKEY_PORT', host: 'env:VALKEY_HOST' },
        mailer: {
          sender: { email: 'env:MAILER_SENDER_EMAIL', name: 'env:MAILER_SENDER_NAME' },
          transport: {
            host: 'env:SMTP_HOST',
            port: 'env:SMTP_PORT',
            secure: true,
            auth: { user: 'env:SMTP_AUTH_USER', pass: 'env:SMTP_AUTH_PASS' },
          },
        },
      },
    },
  },
  cron: {
    records: {
      A: [
        {
          host: 'env:DDNS_HOST:example.com',
          dns: 'env:DDNS_PROVIDER:dondominio',
          api_key: 'env:DDNS_API_KEY:',
          user: 'env:DDNS_USER:',
        },
      ],
    },
    jobs: {
      dns: { expression: '* * * * *', enabled: true, instances: 1 },
      backups: { expression: '0 1 * * *', enabled: true, instances: 1 },
    },
  },
  wireguard: {
    '00.000.00.000': {
      interfaceName: 'wg0',
      listenPort: 51820,
      address: '10.0.0.1/24',
      publicKey: '',
      sshForwardPort: 2222,
      peers: [
        {
          id: 'homelab-a',
          address: '10.0.0.2',
          managementHost: '192.168.1.80',
          publicKey: '',
          allowedIPs: ['10.0.0.2/32'],
          hosts: [],
          instances: [],
          default: true,
        },
      ],
    },
  },
  event: {
    'notification-providers': {
      'default-cluster-mailer-provider': {
        type: 'mailer',
        mailer: {
          sender: { email: 'env:CLUSTER_MAILER_SENDER_EMAIL', name: 'env:CLUSTER_MAILER_SENDER_NAME:Underpost' },
          transport: {
            host: 'env:CLUSTER_MAILER_SMTP_HOST',
            port: 'env:CLUSTER_MAILER_SMTP_PORT:int:587',
            secure: 'env:CLUSTER_MAILER_SMTP_SECURE:bool:false',
            auth: { user: 'env:CLUSTER_MAILER_SMTP_AUTH_USER', pass: 'env:CLUSTER_MAILER_SMTP_AUTH_PASS' },
          },
        },
      },
    },
    events: {
      'wireguard-server-down': {
        probeInterval: '30s',
        alertFor: '5m',
        notifications: [
          {
            'notification-provider-id': 'default-cluster-mailer-provider',
            payload: { subscribers: [{ email: 'admin@default.net', name: 'Admin' }] },
          },
        ],
      },
      'wireguard-spoke-down': {
        probeInterval: '30s',
        alertFor: '2m',
        notifications: [
          {
            'notification-provider-id': 'default-cluster-mailer-provider',
            payload: { subscribers: [{ email: 'admin@default.net', name: 'Admin' }] },
          },
        ],
      },
      'public-ingress-down': {
        probeInterval: '5m',
        alertFor: '5m',
        notifications: [
          {
            'notification-provider-id': 'default-cluster-mailer-provider',
            payload: { subscribers: [{ email: 'admin@default.net', name: 'Admin' }] },
          },
        ],
      },
    },
  },
  users: [
    {
      user: 'root',
      password: '',
      groups: 'wheel',
      keyPath: './engine-private/deploy/id_rsa',
      pubKeyPath: './engine-private/deploy/id_rsa.pub',
      hosts: [{ host: '00.000.00.000', port: 22 }],
    },
  ],
}; /**/

export { DefaultConf };
